#:set omanair_blue (.33, .45, .58)
#:set omanair_white (.95, .95, .95)

<MenuItem@Button>:


<Menu>:
    orientation: 'vertical'
    canvas.before:
        Color:
            rgb: omanair_blue
        Rectangle:
            pos: self.pos
            size: self.size

    MenuItem:
        text: 'Login'
        on_press: root.onLogin()

    MenuItem:
        text: 'Update'
        on_press: root.onUpdate()